FF_RELS = 3.0 3.5 3.6
BF_VER = 0.5.3
MIN_VER = 3.0
MAX_VER = 3.6.*

all:
	@echo "Targets:"
	@echo " xpcom\t\tbuild binaries for this platform"
	@echo " dir\t\tbuild extension directories"
	@echo " xpi\t\tbuild xpi from extension folders"
	@echo " clean\t\tremove all files generated by make"

xpcom:
	cd src && make FF_RELS="$(FF_RELS)"

dir:
	echo Creating extension folders
	mkdir -p scratch && cp -r ext/* scratch
	perl -pi -e "s/%%MINVER%%/$(MIN_VER)/g" scratch/install.rdf
	perl -pi -e "s/%%MAXVER%%/$(MAX_VER)/g" scratch/install.rdf
	perl -pi -e "s/%%VER%%/$(BF_VER)/g" scratch/install.rdf
	cp src/$(MIN_VER)/*.xpt src/*.js scratch/components
	for release in $(FF_RELS); do \
        mkdir -p scratch/lib/$$release && \
        cp src/$$release/bfdnssd.dll scratch/lib/$$release 2>/dev/null|| echo "bfdnssd.dll for FF$$release missing" && \
        cp src/$$release/bfdnssd-darwin-universal.dylib scratch/lib/$$release 2>/dev/null|| echo "bfdnssd-darwin-universal.dylib for FF$$release missing"; \
    done

xpi: dir
	cd scratch && zip -r ../bonjourfoxy-$(BF_VER).xpi *;

clean:
	cd src && make FF_RELS="$(FF_RELS)" clean
	for release in $(FF_RELS); do \
        rm -fr scratch/$$release; \
    done
