Document: bonjourfoxy
Title: Debian bonjourfoxy Manual
Author: <insert document author here>
Abstract: This manual describes what bonjourfoxy is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/bonjourfoxy/bonjourfoxy.sgml.gz

Format: postscript
Files: /usr/share/doc/bonjourfoxy/bonjourfoxy.ps.gz

Format: text
Files: /usr/share/doc/bonjourfoxy/bonjourfoxy.text.gz

Format: HTML
Index: /usr/share/doc/bonjourfoxy/html/index.html
Files: /usr/share/doc/bonjourfoxy/html/*.html


