/* -*- Mode: C; tab-width: 4 -*-
 *
 * Copyright (c) 2009 Apple Computer, Inc. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "nsISupports.idl"

interface IDNSSDService;


[scriptable, function, uuid(E8E81354-2BF5-41BB-BC61-6AED6C88E017)]
interface IDNSSDBrowseListener : nsISupports
{
	void
	onBrowse( in IDNSSDService service, in boolean add, in long interfaceIndex, in long error, in AString serviceName, in AString regtype, in AString domain );
};


[scriptable, function, uuid(4BC9C5DC-0AC4-4BD5-ABDD-75B77947EEA0)]
interface IDNSSDResolveListener : nsISupports
{
	void
	onResolve( in IDNSSDService service, in long interfaceIndex, in long error, in AString fullname, in AString host, in short port, in AString key, in AString value );
};


[scriptable, uuid(7E2EAF8E-FBBE-460E-B838-69D2389BA46F)]
interface IDNSSDService : nsISupports
{
	IDNSSDService
	browse( in long interfaceIndex, in AString regtype, in AString domain, in IDNSSDBrowseListener listener );

	IDNSSDService
	resolve( in long interfaceIndex, in AString name, in AString regtype, in AString domain, in AString key, in IDNSSDResolveListener listener );

	void
	stop();
};
